### ISSUE TITLE
Error when running tests for site-packages install

### ISSUE THREAD

**Issue by ashutoshvarma** [ashutoshvarma/pyxpdf#13]
See the CI run - https://github.com/ashutoshvarma/pyxpdf/runs/990111561
importing  `test_segfault_image_text_image.py` is causing problem

```
Using package from site-packages.
Traceback (most recent call last):
  File "runtests.py", line 213, in import_module
    mod = __import__(modname)
ModuleNotFoundError: No module named 'tests.test_segfault_image_text_image'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "runtests.py", line 661, in <module>
    exitcode = main(sys.argv)
  File "runtests.py", line 598, in main
    test_cases = get_test_cases(test_files, cfg, cov=cov)
  File "runtests.py", line 281, in get_test_cases
    module = import_module(file, cfg, cov=cov)
  File "runtests.py", line 221, in import_module
    mod = __import__(modname)
ModuleNotFoundError: No module named 'tests.test_segfault_image_text_image'
```

**Comment by ashutoshvarma** [comment]
after many attempts, now it seems that i have to rewrite entire tests discovery part to fix this issue
