### ISSUE TITLE
Python Support for python 3.11

### ISSUE THREAD

**Issue by Monotoba** [ashutoshvarma/pyxpdf#46]
Installing on Ubuntu 22.04 in a venv environment using Python 3.11 failed with the following output:
I did just notice that listed python versions on PyPI is 3.8, if > 3.8 is not supported will support for > 3.8 be added anytime soon?

Output from pip intstall pyxpdf:

 Using cached pyxpdf-0.2.3.tar.gz (1.9 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [20 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-6g6ib8ah/pyxpdf_b8e0b2a4c698462d923e318285dcbc38/setup.py", line 165, in <module>
          **setup_extra_options()
            ^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g6ib8ah/pyxpdf_b8e0b2a4c698462d923e318285dcbc38/setup.py", line 98, in setup_extra_options
          ext_modules = setupinfo.ext_modules(
                        ^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g6ib8ah/pyxpdf_b8e0b2a4c698462d923e318285dcbc38/setupinfo.py", line 100, in ext_modules
          get_prebuilt_libxpdf(
        File "/tmp/pip-install-6g6ib8ah/pyxpdf_b8e0b2a4c698462d923e318285dcbc38/get_libxpdf.py", line 91, in get_prebuilt_libxpdf
          lib_dest_path = download_and_extract_libxpdf(download_dir)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-install-6g6ib8ah/pyxpdf_b8e0b2a4c698462d923e318285dcbc38/get_libxpdf.py", line 60, in download_and_extract_libxpdf
          libname = [name for name in filenames if "linux" in name and arch in name][0]
                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
      IndexError: list index out of range
      Building pyxpdf version 0.2.3.
      Latest version of libxpdf is 0.1.3
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by ReMiOS** [comment]
Look into this issue for a workaround
https://github.com/ashutoshvarma/pyxpdf/issues/45

**Comment by Monotoba** [comment]
Thanks I'll check it out this evening.

**Comment by sirk390** [comment]
This issue is caused by parsing this page: "https://github.com/ashutoshvarma/libxpdf/releases"

Github changed its format, and now the code is not working anymore.

It would be much more robust and simpler to extract the release info from the API here:
         https://api.github.com/repos/ashutoshvarma/libxpdf/releases
